# Generated by Django 4.0 on 2022-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('author_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.BigIntegerField()),
                ('weather_state_name', models.CharField(max_length=20)),
                ('wind_direction_compass', models.CharField(max_length=20)),
                ('created', models.CharField(max_length=255)),
                ('applicable_date', models.DateField()),
                ('min_temp', models.CharField(max_length=255)),
                ('max_temp', models.CharField(max_length=255)),
                ('the_temp', models.CharField(max_length=255)),
            ],
        ),
    ]
