# Generated by Django 4.0 on 2022-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weather',
            name='the_temp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
