# Generated by Django 4.0 on 2022-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_alter_weather_created_alter_weather_the_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='the_temp',
            field=models.CharField(max_length=20),
        ),
    ]
