# Generated by Django 4.0 on 2022-01-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0003_alter_weather_created_alter_weather_max_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
