# Generated by Django 4.0 on 2022-02-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0004_dataview_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id_field',
            field=models.IntegerField(),
        ),
    ]
