# Generated by Django 4.0 on 2022-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0005_alter_weather_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id_field',
            field=models.CharField(max_length=20),
        ),
    ]
